/** Gloss stems known to have SiGML under /public/SignFiles/<stem>.sigml */
export const SIGML_WORDS = [
  "0", "1", "10", "100", "11", "12", "13", "2", "3", "4", "5", "6", "7", "8", "9",
  "a", "about", "above", "absorb", "accept", "access", "accident", "accuse", "across",
  "act", "acting", "active", "actor", "actress", "add", "advice", "advise", "aeroplane",
  "afraid", "africa", "after", "afternoon", "age", "agree", "alive", "all", "allah",
  "allow", "alone", "always", "ambulance", "america", "among", "angry", "announce",
  "answer", "any", "anything", "appear", "apple", "appointment", "april", "are", "area",
  "argue", "around", "arrange", "arrest", "arrive", "art", "asia", "askanything",
  "askquestion", "at", "attend", "available", "avoid", "awful", "b", "bad", "badminton",
  "bag", "ball", "bat", "bath", "beautiful", "become", "before", "begin", "behind",
  "bell", "below", "bench", "best", "better", "between", "big", "bird", "black",
  "blackboard", "blue", "boat", "body", "book", "borrow", "bowl", "boxing", "boy",
  "break", "bridge", "bring", "britain", "broom", "brown", "brush", "build", "building",
  "busy", "bye", "c", "call", "can", "cancel", "cannot", "car", "carry", "catch",
  "center", "certificate", "chair", "chalk", "check", "chemistry", "child", "children",
  "christian", "christmas", "church", "cinema", "circle", "circus", "clap", "class",
  "classroom", "climb", "close", "cloud", "clown", "collect", "college", "colour",
  "come", "communicate", "communication", "compare", "computer", "concentrate", "confuse",
  "congratulations", "contact", "continue", "control", "cook", "copy", "correct",
  "council", "count", "cover", "crash", "cricket", "cry", "cup", "cut", "cycle",
  "d", "dance", "date", "day", "deaf", "decrease", "delete", "desk", "detail",
  "develop", "different", "difficult", "discuss", "divide", "doctor", "down", "draw",
  "dream", "drinking", "e", "easy", "eat", "education", "eight", "eighteen", "eleven",
  "email", "empty", "encourage", "end", "engineer", "england", "english", "enjoy",
  "enter", "equal", "eraser", "escape", "evening", "every", "everyday", "exam",
  "examination", "examine", "example", "expensive", "experience", "f", "factory",
  "fail", "fall", "far", "farmer", "fat", "father", "fear", "february", "feed",
  "feel", "few", "fifteen", "fight", "fill", "finish", "five", "flood", "floor",
  "fly", "food", "forever", "forgive", "form", "four", "fourteen", "france", "friday",
  "fruit", "g", "germany", "get", "girl", "give-me", "go", "gold", "good", "greece",
  "green", "grey", "h", "half-past", "hang", "hardofhearing", "havealook", "he",
  "health", "hearing", "hello", "help-me", "help-you", "her", "here", "hers", "hill",
  "him", "himself", "hindi", "hindu", "his", "hockey", "hold", "home", "hospital",
  "hot", "hour", "house", "how", "howareyou", "howmany", "howmuch", "hundred", "hungry",
  "i", "idea", "ignore", "important", "impossible", "improve", "in", "increase",
  "informus", "injection", "intelligent", "interesting", "internet", "interpreter",
  "iunderstand", "j", "january", "jealous", "jesus", "join", "jump", "june", "k",
  "keep", "key", "keyboard", "kite", "know", "knowledge", "l", "laboratory", "ladder",
  "languages", "late", "later", "laugh", "learn", "leave", "lecturer", "lend", "less",
  "letter", "level", "library", "light", "like", "line", "list", "little", "lock",
  "long", "lose", "loss", "loud", "love", "m", "man", "mango", "many", "march",
  "married", "may", "maybe", "me", "meet", "mind", "mistake", "monday", "money",
  "more", "morning", "mother", "my", "n", "name", "namewhat", "national", "near",
  "need", "needle", "never", "new", "news", "next", "nextyear", "nice", "night",
  "nine", "nineteen", "no", "none", "not", "now", "number", "nurse", "o", "offer",
  "office", "officer", "often", "old", "olympics", "on", "one", "onion", "open",
  "operation", "or", "orange", "order", "our", "ourself", "out", "over", "own",
  "p", "pay", "pen", "person", "phone", "pick", "pink", "plan", "please", "possible",
  "practice", "prayer", "pretend", "print", "problem", "profit", "provide", "purple",
  "q", "question", "quick", "quiet", "quote", "r", "rain", "reach", "read", "ready",
  "receive", "reception", "rectangle", "red", "regular", "relate", "relation", "remind",
  "remove", "repeat", "research", "responsibility", "responsible", "result", "roof",
  "run", "s", "sad", "same", "save", "say", "science", "scotland", "screen", "search",
  "see", "send", "seven", "seventeen", "shake", "short", "sign", "silver", "six",
  "sixteen", "slow", "small", "soft", "sorry", "spelling", "stay", "stop", "stubborn",
  "stupid", "sunday", "switzerland", "t", "table", "tablet", "take", "talk", "tall",
  "taste", "taxi", "teach", "teacher", "teachme", "teachyou", "tear", "tease",
  "technical", "teeth", "temple", "ten", "tennis", "thankyou", "that", "their",
  "them", "themselves", "then", "there", "these", "they", "think", "thirsty", "thirteen",
  "this", "those", "thread", "three", "throw", "thumb", "thursday", "ticket", "tie",
  "tight", "time", "today", "together", "tomato", "tomorrow", "tools", "touch", "toward",
  "town", "track", "train", "transport", "travel", "tree", "trophy", "truck", "truth",
  "try", "tuesday", "turn", "tv", "twelve", "twenty", "two", "u", "ugly", "umbrella",
  "under", "understand", "uniform", "university", "until", "up", "us", "v", "van",
  "vegetable", "vegetables", "very", "video", "visit", "volleyball", "w", "wait",
  "walk", "want", "was", "wash", "waste", "water", "we", "weapon", "wear", "weather",
  "wednesday", "week", "weigh", "weight", "welcome", "well", "west", "what", "wheat",
  "when", "where", "which", "white", "who", "why", "wide", "will", "win", "wire",
  "wish", "with", "without", "woman", "word", "work", "worry", "worse", "worst",
  "write", "wrong", "x", "y", "yeah", "yellow", "yes", "yesterday", "you", "your",
  "yours", "yourself", "yourselves", "z", "zebra-crossing", "zero", "zoo",
] as const

export const SIGML_WORD_SET = new Set<string>(SIGML_WORDS as unknown as string[])
